export enum StatusSubmissao {
  SUBMETIDA = "SUBMETIDA",
  EM_AVALIACAO = "EM_AVALIACAO",
  APROVADA = "APROVADA",
  APROVADA_COM_RESSALVAS = "APROVADA_COM_RESSALVAS",
  REJEITADA = "REJEITADA",
  EM_REVISÃO = "EM_REVISÃO"
}

